
name: telegram

on:
  push:
    branches: [ main ]  
  pull_request:
    types: [assigned, opened, synchronize, reopened]     
jobs:
  build:   
    runs-on: ubuntu-latest    
    steps:        
    - uses: avkviring/telegram-github-action@v0.0.13
      env:
        telegram_to: 483494219  
        telegram_token: 1766537054:AAEuVDu3UBgdweRDafrrDpj2vcya1Dn_fwU
        event: ${{ toJson(github.event) }}
